### ISSUE TITLE
Viewer.setPanorama -> Cannot add property transition, object is not extensible

### ISSUE THREAD

**Issue by rohitCodeBuddy** [mistic100/Photo-Sphere-Viewer#1291]
### Describe the bug

viewer crashes if manually changing scene using
`  viewer
      ?.setPanorama(IMAGES[nextStep], {
        zoom: 0,
        position: {
          yaw: 1,
          pitch: 1,
        },
        transition: true,
      })
      .then(() => setStep(nextStep));`

### Online demo URL

[DEMO URL](https://codesandbox.io/p/sandbox/delicate-firefly-nvkmdf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluxs4za500063b6hf4d34jzv%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluxs4za400023b6h10f7kc2a%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluxs4za400033b6hy5a3eq9q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluxs4za400053b6hzil6hsbe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluxs4za400023b6h10f7kc2a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluxs4za400013b6h38d9zkoz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluxs4za400023b6h10f7kc2a%2522%252C%2522activeTabId%2522%253A%2522cluxs4za400013b6h38d9zkoz%2522%257D%252C%2522cluxs4za400053b6hzil6hsbe%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluxs4za400043b6hmtbf76ug%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluxs4za400053b6hzil6hsbe%2522%252C%2522activeTabId%2522%253A%2522cluxs4za400043b6hmtbf76ug%2522%257D%252C%2522cluxs4za400033b6hy5a3eq9q%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluxs4za400033b6hy5a3eq9q%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
### Photo Sphere Viewer version

5.7.2

### Plugins loaded

None

### OS & browser

Mac OS, Chrome

**Comment by mistic100** [comment]
This seems to be a problem with React Photo Sphere. There is a binding to the "src" property here https://github.com/Elius94/react-photo-sphere-viewer/blob/main/src/index.tsx#L484-L488

In your case "setPanorama" is called twice (once by your code and once by the react wrapper). Additionally the react wrapper calls it with the initial "options" which seems frozen, so it crash.

I suggest you ask the wrapper author how to disable this binding in order to manually change the scenes.

**Comment by rohitCodeBuddy** [comment]
Thanks !! for the help 👍

**Comment by bakermanbrian** [comment]
@rohitCodeBuddy how did you work around this issue on your end?

**Comment by Elius94** [comment]
Hi,
fixed in release 6.0.0 (react-photo-sphere-viewer)

[![Edit sleepy-williamson-x7s9nv](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/delicate-firefly-nvkmdf?file=%2Fsrc%2Findex.tsx)

**Comment by mistic100** [comment]
FYI your sandbox uses version `5.0.2-psv5.7.1` and thus still have the error. Switching to 6.0.0 indeed fix the issue.

However I noticed there a second loader briefly displayed because the component thinks the url changed when calling `setStep`. PSV core does not check if the panorama is different when calling `setPanorama` (and it could be a legitimiate usage...).

**Comment by Elius94** [comment]
Ops, Thank you for notice me!
I've used the old link.

[![Edit gifted-dewdney-4646l2](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/gifted-dewdney-4646l2)

This is the real sandbox

P.S: I'm working on the double loader you mentioned. Thanks
