### ISSUE TITLE
Markers in MarkersPlugin cause node markers from VirtualTourPlugin to disappear

### ISSUE THREAD

**Issue by mikepianka** [mistic100/Photo-Sphere-Viewer#734]
Sorry for all the questions lately! Is there an official example of a virtual tour using manual `positionMode` and markers `renderMode`? I am trying to set up a small example and while I can see my node on the compass, I cannot see it in the scene.

![image](https://user-images.githubusercontent.com/47948499/186519313-1ecd3ee6-7f0d-47df-8441-d2699b61ffb8.png)

It is defined like this:
```js
        [
          VirtualTourPlugin,
          {
            dataMode: "client",
            positionMode: "manual",
            renderMode: "markers",
            startNodeId: "node-1",
            nodes: [
              {
                id: "node-1",
                panorama: "./assets/pano.jpg",
                name: "One",
                links: [
                  {
                    nodeId: "node-2",
                    latitude: 0,
                    longitude: 0,
                    markerStyle: {
                      html: null, // needed for other marker styles
                      id: "temppp",
                      square: 30,
                      latitude: "0deg",
                      longitude: "0deg",
                      svgStyle: {
                        fill: "rgba(200, 0, 0, 0.2)",
                        stroke: "rgba(200, 0, 50, 0.8)",
                        strokeWidth: "2px",
                      },
                    },
                  },
                ],
              },
              {
                id: "node-2",
                panorama: "./assets/pano_2.jpg",
                name: "Two",
                links: [
                  { nodeId: "node-1", latitude: "0deg", longitude: "0deg" },
                ],
              },
            ],
          },
        ],
```

**Comment by mistic100** [comment]
Looks like a long lasting bug in the markers plugin : `square` should be transformed to `rect` as there is not squares in SVG. Use `rect: [30, 30]` instead untilf it is fixed.

-----

You should remove `id`, `longitude`, `latitude` from the marker style definition, just for the sake of cleanliness.  
Reference : https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/plugins/virtual-tour/index.js#L590-L598

**Comment by mistic100** [comment]
> You should remove `id`, `longitude`, `latitude` from the marker style definition, just for the sake of cleanliness. Reference : https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/plugins/virtual-tour/index.js#L590-L598

Okay, it is missing a `Partial` in the type definition, I'll add it.

**Comment by mikepianka** [comment]
Thanks, but after those changes I still don't see the square. 

Code:
```js
        [
          VirtualTourPlugin,
          {
            dataMode: "client",
            positionMode: "manual",
            renderMode: "markers",
            startNodeId: "node-1",
            nodes: [
              {
                id: "node-1",
                panorama: "./assets/pano.jpg",
                name: "One",
                links: [
                  {
                    nodeId: "node-2",
                    latitude: 0,
                    longitude: 0,
                    markerStyle: {
                      html: null, // needed for other marker styles
                      rect: [30, 30],
                      svgStyle: {
                        fill: "rgba(200, 0, 0, 0.2)",
                        stroke: "rgba(200, 0, 50, 0.8)",
                        strokeWidth: "2px",
                      },
                    },
                  },
                ],
              },
              {
                id: "node-2",
                panorama: "./assets/pano_2.jpg",
                name: "Two",
                links: [
                  { nodeId: "node-1", latitude: "0deg", longitude: "0deg" },
                ],
              },
            ],
          },
        ],
```

**Comment by mistic100** [comment]
Well post a repro on jsfiddle. I juste tested it on the example file, it works for me.

**Comment by mikepianka** [comment]
I actually just noticed that the red pin that should be on the lighthouse is missing in the virtual tour example in the docs. If you hover the cursor in that spot the tooltip displays but the marker is not visible. Same problem?

![image](https://user-images.githubusercontent.com/47948499/186547191-22148134-85ef-4eec-a437-07ea3d6d9aa8.png)

**Comment by mistic100** [comment]
No that's just because the URL was wrong, I fixed the demo.

**Comment by mikepianka** [comment]
OK I figured out the problem. If you have markers defined in the marker plugin, they will cause any node markers from the virtual tour to not be shown. If this is not possible an error should be thrown. I think it would be a good idea to leave it possible though so that a reoccurring general marker could be shown as an overlay on all virtual tour images.

First example of virtual tour in manual mode with markers working fine: https://jsfiddle.net/3vjhrnpy

Second example where adding a circle marker causes the virtual tour markers to disappear: https://jsfiddle.net/3vjhrnpy/1/

**Comment by mistic100** [comment]
That's a tricky problem because :
- the markers plugin calls `setMarkers` on init, which clear all markers
- the virtual tour plugin calls `clearMarkers` when changing node (and then `setMarkers` if the node has additional markers)

I think this behavior makes sense if we consider each node independant in term of configuration.

What you can do is configure the same [`markers`](https://photo-sphere-viewer.js.org/plugins/plugin-virtual-tour.html#markers) on each node.

**Comment by mistic100** [comment]
I will add a warning and clear the config if this case happens

> No default markers can be configured on Markers plugin when using VirtualTour plugin. Consider defining `markers` on each tour node.
